name: carease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  easy_radio: ^0.0.3
  alert_info: ^0.0.6
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "lib/Images/app_icon_1024.jpg"

flutter:
  uses-material-design: true
  assets:
    - lib/Images/
    - Fonts/
  fonts:
    - family: MyFont
      fonts:
        - asset: Fonts/my_font/my_font_light.ttf
        - asset: Fonts/my_font/my_font_bold.ttf

    - family: Poppins
      fonts:
        - asset: Fonts/poppins/Poppins-Bold.ttf
        - asset: Fonts/poppins/Poppins-Medium.ttf
        - asset: Fonts/poppins/Poppins-Regular.ttf
        - asset: Fonts/poppins/Poppins-Thin.ttf

    - family: SF-Pro
      fonts:
        - asset: Fonts/sf_pro/SF-Pro-Rounded-Bold.otf
        - asset: Fonts/sf_pro/SF-Pro-Rounded-Light.otf
        - asset: Fonts/sf_pro/SF-Pro-Rounded-Medium.otf
        - asset: Fonts/sf_pro/SF-Pro-Rounded-Regular.otf
        - asset: Fonts/sf_pro/SF-Pro-Rounded-Thin.otf